# Generated by Django 5.0.6 on 2024-09-28 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bs_day', models.IntegerField(default=1)),
                ('bs_month', models.IntegerField(default=1)),
                ('bs_year', models.IntegerField(default=2080)),
                ('bs_month_en', models.CharField(max_length=50)),
                ('is_holiday', models.BooleanField(default=False)),
                ('bs_month_np', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_np', models.CharField(blank=True, max_length=255, null=True)),
                ('is_holiday', models.BooleanField(default=False)),
                ('event_en', models.CharField(blank=True, max_length=255, null=True)),
                ('holiday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='holidays.holiday')),
            ],
        ),
    ]
