# Generated by Django 5.0.6 on 2024-09-28 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_en',
        ),
    ]
