# Generated by Django 5.0.6 on 2024-09-27 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holiday',
            name='date',
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='description',
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='name',
        ),
        migrations.AddField(
            model_name='holiday',
            name='bs_day',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='holiday',
            name='bs_month',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='holiday',
            name='bs_month_np',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='holiday',
            name='bs_year',
            field=models.IntegerField(default=2080),
        ),
        migrations.AddField(
            model_name='holiday',
            name='is_holiday',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_np', models.CharField(default='अज्ञात घटना', max_length=255)),
                ('is_holiday', models.BooleanField(default=False)),
                ('holiday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='holidays.holiday')),
            ],
        ),
    ]
