# Generated by Django 5.0.6 on 2024-09-27 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0003_event_event_en_holiday_bs_month_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holiday',
            name='bs_month_np',
        ),
    ]
