# Generated by Django 5.0.6 on 2024-09-28 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0004_remove_holiday_bs_month_np'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='bs_month_np',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
