# Generated by Django 5.0.6 on 2024-09-30 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0004_alter_holiday_unique_together'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(fields=('holiday', 'event_en', 'event_np'), name='unique_event_per_holiday'),
        ),
    ]
