# Generated by Django 5.0.6 on 2024-09-28 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0005_holiday_bs_month_np'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='holiday',
            unique_together={('bs_day', 'bs_month', 'bs_year')},
        ),
    ]
