# Generated by Django 5.0.6 on 2024-10-03 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0005_event_unique_event_per_holiday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='is_holiday',
            new_name='event_is_holiday',
        ),
    ]
