# Generated by Django 5.0.6 on 2024-09-28 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0006_alter_holiday_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='holiday',
            unique_together=set(),
        ),
    ]
