# Generated by Django 5.0.6 on 2024-10-03 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0006_rename_is_holiday_event_event_is_holiday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_is_holiday',
            new_name='is_holiday',
        ),
    ]
