# Generated by Django 5.0.6 on 2024-10-04 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0007_rename_event_is_holiday_event_is_holiday'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='event',
            name='unique_event_per_holiday',
        ),
        migrations.AlterUniqueTogether(
            name='holiday',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='event',
            name='holiday',
        ),
        migrations.AddField(
            model_name='holiday',
            name='events',
            field=models.ManyToManyField(related_name='holidays', to='holidays.event'),
        ),
    ]
