# Generated by Django 5.0.6 on 2024-10-08 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0008_remove_event_unique_event_per_holiday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='weekdayStrEn',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='holiday',
            name='weekdayStrNp',
            field=models.CharField(default='unknown', max_length=60),
        ),
    ]
