# Generated by Django 5.0.6 on 2024-10-08 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0009_holiday_weekdaystren_holiday_weekdaystrnp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='holiday',
            old_name='weekdayStrEn',
            new_name='weekday_En',
        ),
        migrations.RenameField(
            model_name='holiday',
            old_name='weekdayStrNp',
            new_name='weekday_Np',
        ),
    ]
